### ISSUE TITLE
Lowering the requirement for transformers library

### ISSUE THREAD

**Issue by rubik** [Xe/pathwalk#8]
I'm using this excellent library in one of my projects. Currently my project runs on GHC 7.10.2 and all is well. In an effort to make it compatible with GHC 7.8.4 I run into a dependency issue with your package.

`pathwalk` requires `transformers>=0.4`, but Stack's latest build plan for GHC 7.8 (lts-2.22) only contains `transformers==0.3.0.0`. Would it be possible to lower the requirement? I briefly looked at the code but couldn't determine if `pathwalk` used new functionality from `transfomers==0.4`.

**Comment by chadaustin** [comment]
I have no reason to believe it wouldn't work on 0.3.0.0 -- if you try it and it works, let's go ahead and lower the requirement!

**Comment by chadaustin** [comment]
Hi @rubik, I relaxed the dependency on transformers.  I don't have a way to manually test, but I don't see anything that would cause this to fail.

Care to try pathwalk 0.3.1.1 ( http://hackage.haskell.org/package/pathwalk-0.3.1.1 ) and see if it helps?

**Comment by rubik** [comment]
Thanks! I'll check right now.

**Comment by rubik** [comment]
GHC 7.8.4 complains that Monoid isn't defined. I made a PR to fix the issue. I can confirm that after making this change, the library works as expected.

**Comment by chadaustin** [comment]
New version on Hackage: hopefully it works on GHC 7.8!  http://hackage.haskell.org/package/pathwalk-0.3.1.2

**Comment by rubik** [comment]
Great! Thank you so much!
